In [1]:
import numpy as np
import torch

In [2]:
#Production of apples and oranges in 5 regions based on below 3 parameters
#input (temp, rainfall, humidity) for 5 regions
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [4]:
#converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
#generating random weights and baises
w = torch.randn(2, 3, requires_grad=True) #weight matrix of size 2x3
b = torch.randn(2, requires_grad=True) # bias vector of size 2
print(w)
print(b)

tensor([[-0.0807,  2.8728, -1.1009],
        [ 0.4843,  2.1051, -0.5995]], requires_grad=True)
tensor([-1.0090, -0.3623], requires_grad=True)


In [15]:
def model(x):
    return x @ w.t() + b # @ represents matrix multiplication in torch

In [ ]:
#generating predictions by passing input values to our model function
preds = model(inputs)
print(preds)

tensor([[138.2371, 150.2567],
        [173.9939, 190.5920],
        [313.0696, 289.0884],
        [ 73.5555, 117.3753],
        [192.1463, 193.1813]], grad_fn=<AddBackward0>)


In [17]:
# compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
diff = preds - targets
torch.sqrt(torch.sum(diff*diff)/ diff.numel()) # mean squred error
# numel method is used to count the total number of elements in any tensor/ndimention matrix

NameError: name 'preds' is not defined

In [28]:
# Mean Squared error
def mse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/ diff.numel()

In [29]:
#computing loss
loss = mse(preds, targets)
print(loss)

tensor(11447.3320, grad_fn=<DivBackward0>)


In [30]:
#computing gradients
loss.backward()

In [32]:
#gradients for weights
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.0807,  2.8728, -1.1009],
        [ 0.4843,  2.1051, -0.5995]], requires_grad=True)
tensor([[ 8551.9111, 10094.7197,  5778.3262],
        [ 8181.6187,  8950.9365,  5280.9258]])
tensor([-1.0090, -0.3623], requires_grad=True)
tensor([102.0005,  96.0987])


In [33]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [34]:
w, b

(tensor([[-0.1662,  2.7718, -1.1587],
         [ 0.4025,  2.0156, -0.6523]], requires_grad=True),
 tensor([-1.0100, -0.3632], requires_grad=True))

In [37]:
#let's verify that the loss is actuallu lower
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(7956.3213, grad_fn=<DivBackward0>)


In [ ]:
w.grad.zero_()
b.grad.zero_()
#reseting the gradient to zero so that it will start calculation again and not continue on old gradient
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
#train for 100 Epochs
# process of training model 1 time is call an
for i in range(20000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [54]:
#calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.4989, grad_fn=<DivBackward0>)


In [55]:
#Prediction
preds

tensor([[ 56.9976,  70.2482],
        [ 82.3119, 100.7083],
        [118.7205, 132.9685],
        [ 21.1026,  37.0228],
        [101.8934, 119.1281]], grad_fn=<AddBackward0>)

In [46]:
#target
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])